sudo: required
services:
  - docker
 
before_install:
  - docker build -t hamdiceylan/aws-docker-deploy -f Dockerfile.dev .
 
script:
  - docker run hamdiceylan/aws-docker-deploy npm run test -- --coverage
