sudo: required
services:
  - docker
 
before_install:
  - docker build . -t hamdiceylan/aws-docker-deploy 
 
#Tell Travis to execute tests (-- -- Coverage will exit npm run test and print out the code coverage)
script:
  - docker run -p 8080:80 hamdiceylan/aws-docker-deploy 