version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
     build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]